/*
 * This file has been automatically generated by the jrl-cmakemodules.
 * Please see https://github.com/jrl-umi3218/jrl-cmakemodules/blob/master/config.hh.cmake for details.
*/

#ifndef ROS_QUALISYS_CONFIG_HH
# define ROS_QUALISYS_CONFIG_HH

// Package version (header).
# define ROS_QUALISYS_VERSION_UNKNOWN_TAG 0 // Used to mention that the current version is unknown.
# define ROS_QUALISYS_VERSION "1.0.0"
# define ROS_QUALISYS_MAJOR_VERSION 1
# define ROS_QUALISYS_MINOR_VERSION 0
# define ROS_QUALISYS_PATCH_VERSION 0

#define ROS_QUALISYS_VERSION_AT_LEAST(major, minor, patch) (ROS_QUALISYS_MAJOR_VERSION>major || (ROS_QUALISYS_MAJOR_VERSION>=major && \
                                                             (ROS_QUALISYS_MINOR_VERSION>minor || (ROS_QUALISYS_MINOR_VERSION>=minor && \
                                                                                                     ROS_QUALISYS_PATCH_VERSION>=patch))))

#define ROS_QUALISYS_VERSION_AT_MOST(major, minor, patch) (ROS_QUALISYS_MAJOR_VERSION<major || (ROS_QUALISYS_MAJOR_VERSION<=major && \
                                                            (ROS_QUALISYS_MINOR_VERSION<minor || (ROS_QUALISYS_MINOR_VERSION<=minor && \
                                                                                                     ROS_QUALISYS_PATCH_VERSION<=patch))))

// Handle portable symbol export.
// Defining manually which symbol should be exported is required
// under Windows whether MinGW or MSVC is used.
//
// The headers then have to be able to work in two different modes:
// - dllexport when one is building the library,
// - dllimport for clients using the library.
//
// On Linux, set the visibility accordingly. If C++ symbol visibility
// is handled by the compiler, see: http://gcc.gnu.org/wiki/Visibility
//
// Explicit template instantiation on Windows need to add
// dllexport on the definition and dllimport on the declaration.
// The XXX_EXPLICIT_INSTANTIATION_DECLARATION_DLLAPI macro
// should be set on the declaration while
// the XXX_EXPLICIT_INSTANTIATION_DEFINITION_DLLAPI macro
// should be set on the definition.
# if defined _WIN32 || defined __CYGWIN__
// On Microsoft Windows, use dllimport and dllexport to tag symbols.
#  define ROS_QUALISYS_DLLIMPORT __declspec(dllimport)
#  define ROS_QUALISYS_DLLEXPORT __declspec(dllexport)
#  define ROS_QUALISYS_DLLLOCAL
#  define ROS_QUALISYS_EXPLICIT_INSTANTIATION_DECLARATION_DLLIMPORT __declspec(dllimport)
#  define ROS_QUALISYS_EXPLICIT_INSTANTIATION_DECLARATION_DLLEXPORT
#  define ROS_QUALISYS_EXPLICIT_INSTANTIATION_DEFINITION_DLLIMPORT __declspec(dllimport)
#  define ROS_QUALISYS_EXPLICIT_INSTANTIATION_DEFINITION_DLLEXPORT __declspec(dllexport)
# else
// On Linux, for GCC >= 4, tag symbols using GCC extension.
#  if __GNUC__ >= 4
#   define ROS_QUALISYS_DLLIMPORT __attribute__ ((visibility("default")))
#   define ROS_QUALISYS_DLLEXPORT __attribute__ ((visibility("default")))
#   define ROS_QUALISYS_DLLLOCAL  __attribute__ ((visibility("hidden")))
#   define ROS_QUALISYS_EXPLICIT_INSTANTIATION_DECLARATION_DLLIMPORT __attribute__ ((visibility("default")))
#   define ROS_QUALISYS_EXPLICIT_INSTANTIATION_DECLARATION_DLLEXPORT __attribute__ ((visibility("default")))
#   define ROS_QUALISYS_EXPLICIT_INSTANTIATION_DEFINITION_DLLIMPORT
#   define ROS_QUALISYS_EXPLICIT_INSTANTIATION_DEFINITION_DLLEXPORT
#  else
// Otherwise (GCC < 4 or another compiler is used), export everything.
#   define ROS_QUALISYS_DLLIMPORT
#   define ROS_QUALISYS_DLLEXPORT
#   define ROS_QUALISYS_DLLLOCAL
#   define ROS_QUALISYS_EXPLICIT_INSTANTIATION_DECLARATION_DLLIMPORT
#   define ROS_QUALISYS_EXPLICIT_INSTANTIATION_DECLARATION_DLLEXPORT
#   define ROS_QUALISYS_EXPLICIT_INSTANTIATION_DEFINITION_DLLIMPORT
#   define ROS_QUALISYS_EXPLICIT_INSTANTIATION_DEFINITION_DLLEXPORT
#  endif // __GNUC__ >= 4
# endif // defined _WIN32 || defined __CYGWIN__

# ifdef ROS_QUALISYS_STATIC
// If one is using the library statically, get rid of
// extra information and use standard explicit template
// instantiation keyword.
#  define ROS_QUALISYS_DLLAPI
#  define ROS_QUALISYS_LOCAL
#  define ROS_QUALISYS_EXPLICIT_INSTANTIATION_DECLARATION extern template
# else
// Depending on whether one is building or using the
// library define DLLAPI to import or export and
// define the right explicit template instantiation keyword.
#  ifdef ros_qualisys_EXPORTS
#   define ROS_QUALISYS_DLLAPI ROS_QUALISYS_DLLEXPORT
#   define ROS_QUALISYS_EXPLICIT_INSTANTIATION_DECLARATION_DLLAPI ROS_QUALISYS_EXPLICIT_INSTANTIATION_DECLARATION_DLLEXPORT
#   define ROS_QUALISYS_EXPLICIT_INSTANTIATION_DEFINITION_DLLAPI ROS_QUALISYS_EXPLICIT_INSTANTIATION_DEFINITION_DLLEXPORT
#  else
#   define ROS_QUALISYS_DLLAPI ROS_QUALISYS_DLLIMPORT
#   define ROS_QUALISYS_EXPLICIT_INSTANTIATION_DECLARATION_DLLAPI ROS_QUALISYS_EXPLICIT_INSTANTIATION_DECLARATION_DLLIMPORT
#   define ROS_QUALISYS_EXPLICIT_INSTANTIATION_DEFINITION_DLLAPI ROS_QUALISYS_EXPLICIT_INSTANTIATION_DEFINITION_DLLIMPORT
#  endif // ROS_QUALISYS_EXPORTS
#  define ROS_QUALISYS_LOCAL ROS_QUALISYS_DLLLOCAL
# endif // ROS_QUALISYS_STATIC
#endif //! ROS_QUALISYS_CONFIG_HH
